name: Daily Malware DB Update

on:
  schedule:
    # Tatakbo tuwing 12:00 AM UTC araw-araw
    - cron: '0 1 * * *'
  workflow_dispatch: # Para pwede mong i-run manual kung gusto mo

permissions:
  contents: write

jobs:
  update-hashes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run update script
        run: python update_malware.py

      - name: Commit and push changes
        run: |
          git config --global user.name "AntiScam-Bot"
          git config --global user.email "bot@antiscam.local"
          git add malware_db.json
          # Magcocommit lang kung may nabago
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update malware signatures" && git push)
